### ISSUE TITLE
Applicatives don't support keyword args

### ISSUE THREAD

**Issue by jackfirth** [lexi-lambda/functional#3]
The expression `((pure some-proc) #:keyword some-applicative)` raises "application: procedure does not accept keyword arguments". Here's a full program that raises the error:

```racket
#lang racket
(require data/applicative
         megaparsack
         megaparsack/text)

(define (foo #:keyword bar) bar)
((pure foo) #:keyword integer/p)
```

**Comment by lexi-lambda** [comment]
I think this would require changing the `gen:applicative` interface. It might be possible to do in a backwards-compatible way by adding a new `keyword-apply` method to the interface, then defining `apply` as a fallback in terms of `keyword-apply`, but you could implement both to provide better performance.

**Comment by lexi-lambda** [comment]
I started implementing this, got most of the way done with it, then realized it’s probably a bad idea. Applicative functors have order to them, so by-position arguments make sense. Keyword arguments don‘t, really.

Consider this example:

```racket
((pure f) #:foo integer/p #:bar (char/p #\,))
```

One would likely expect that the above parser would parse an integer, then a comma, then pass the results to the `#:foo` and `#:bar` keyword arguments for `f`. However, this won’t actually happen. Instead, it will parse a comma first, *then* an integer. This is because `#:bar` is `keyword<?` `#:foo`, and `make-keyword-procedure` canonicalizes keyword ordering using `keyword<?`.

In general, though, the order of keyword arguments should never matter, which is incompatible with applicative functors. The recommendation is to do one of these instead:

```racket
((pure (λ (x) (foo #:keyword x))) integer/p)

(do [i <- integer/p]
    (pure (foo #:keyword i)))
```

With a lambda shorthand, the first becomes much more palatable.

An applicative shorthand syntactic form (read: idiom brackets) could support these more directly by guaranteeing that the order that keywords are supplied will be the order they are invoked, as well as supporting “ignoring” certain arguments in the output like `*>` and `<*` from Haskell. For now, though, I’m marking this as wontfix.

**Comment by jackfirth** [comment]
I wasn't aware that `make-keyword-procedure` sorts the keywords first, that does pretty much shoot down this idea. I worked around this issue by using `fancy-app` to wrap it with a lambda which works just fine.
